/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Usuario
 */
public class TextoWizard extends javax.swing.JFrame {

    /**
     * Creates new form TextoWizard
     */
    public TextoWizard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtF2 = new javax.swing.JTextField();
        jtF1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtF2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtF2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtF2FocusLost(evt);
            }
        });
        jtF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtF2ActionPerformed(evt);
            }
        });

        jtF1.setText("ffssd123e");
        jtF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtF1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtF1FocusLost(evt);
            }
        });
        jtF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtF1ActionPerformed(evt);
            }
        });
        jtF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtF1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtF1KeyTyped(evt);
            }
        });

        jLabel1.setText("Numero de Cuenta");

        jButton1.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtF2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jtF1))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(79, 79, 79)
                .addComponent(jtF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtF1ActionPerformed

    private void jtF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtF2ActionPerformed

    private void jtF2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtF2FocusGained
        // TODO add your handling code here:
        jtF2.setBackground(Color.GREEN);
    }//GEN-LAST:event_jtF2FocusGained

    private void jtF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtF1FocusGained
        // TODO add your handling code here:
        jtF1.setBackground(Color.GREEN);
    }//GEN-LAST:event_jtF1FocusGained

    private void jtF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtF1FocusLost
        // TODO add your handling code here:
        jtF1.setBackground(Color.WHITE);
    }//GEN-LAST:event_jtF1FocusLost

    private void jtF2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtF2FocusLost
        // TODO add your handling code here:
        jtF2.setBackground(Color.WHITE);
    }//GEN-LAST:event_jtF2FocusLost

    private void jtF1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtF1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtF1KeyPressed

    private void jtF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtF1KeyTyped
        // TODO add your handling code here:
        
        
        //Se le asigna a k el valor de la tecla presionada
        int k = evt.getKeyChar();
        
        if(k >= 32 && k <=47 || k >= 58 && k<= 255){
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
        
        
        if(jtF1.getText().length() >= 9 ){
            
            evt.consume();
        }
        
        
    }//GEN-LAST:event_jtF1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextoWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextoWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextoWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextoWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextoWizard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtF1;
    private javax.swing.JTextField jtF2;
    // End of variables declaration//GEN-END:variables
}
